### ISSUE TITLE
Manual assembly plugin for android

### ISSUE THREAD

**Issue by sanekt197** [sjemens/qsqlcipher-qt5#1]
It was required to use an encrypted base in the mobile application for android.. 
Do not advise how to build a working plugin for Android arm? Could you post a guide? I urgently need, but I can not really collect
I have problems at the stage of the assembly sqlcipher for arm android :(

P.S. Ubuntu 18.04; Qt5.12; ndk 19; target android 4.1 and higher

**Comment by sjemens** [comment]
Hi @sanekt197,
first you need to cross compile the openssl and sqlcipher libraries for the target platforms. I am sorry to say that I do not have an easy tutorial as I am not currently programming for mobile platforms. When time permits I will set up a development machine per your requirements and I will get back to you when I have something constructive to say.

**Comment by sanekt197** [comment]
Thank you very much, would be very grateful. A simple manual would be useful to many.
Openssl I can assemble cross-platform, but sqlcipher is not very

**Comment by sjemens** [comment]
I have a new branch for android [here](https://github.com/sjemens/qsqlcipher-qt5/tree/android).
See README for instructions. See [this](https://github.com/sjemens/sqlcipher/tree/android) if you want to build your own libraries.
Let me know if this works for you

**Comment by sjemens** [comment]
I am closing this for now. Feel free to ask any more questions here if I can help some more.

**Comment by sanekt197** [comment]
Oh, sorry, I forgot. Yes, everything turned out to collect, thank you very much!
