### ISSUE TITLE
Trying to read the database from an external program

### ISSUE THREAD

**Issue by abhatem** [sjemens/qsqlcipher-qt5#11]
Hello, 

I am trying to read a file created with this plugin.
I first tried with the sqlcipher (version "3.15.2 2016-11-28") command on ubuntu 20.04 after calling 

```
sqlite> PRAGMA key='somekey'
```

after running a SELECT query, I get
``` 
Error: file is encrypted or is not a database
```
trying it with the DB Browser (about dialog below) for SQLite
![image](https://user-images.githubusercontent.com/5391214/102282990-32ed5600-3f3a-11eb-9743-e46532d9f7d1.png)
![image](https://user-images.githubusercontent.com/5391214/102282673-9cb93000-3f39-11eb-9be4-a1d2d0552693.png)

It also doesn't seem to accept the key (same one I'm using when opening from Qt). I tried it with the "SQLCipher 3 defaults" and the "SQLCipher 4 defaults".

I am using the Qt 5.12 version with Qt 5.12.10

Do you have any hints here?

**Comment by sjemens** [comment]
Are you sure the database is encrypted? Did you try opening it without a key?
If yes, then how did you set the key in Qt? If you are using a QSqlQuery does it return success? Is the `PRAGMA key='.....'` the first thing after opening the database connection? 

My plugin in Qt 5.12 uses the system's sqlcipher so if you are using ubuntu 20.04 this is sqlcipher 3.4.1
