### ISSUE TITLE
[Qt6 branch] pull request

### ISSUE THREAD

**Issue by faizol** [sjemens/qsqlcipher-qt5#9]
Hi,

I made some changes to make this driver compilable with Qt6 beta4. It passed the test that comes with the code, but I'm not sure if there are other deeper changes needed to be done to make it fully compatible for the upcoming Qt6. Is it possible for the code to be reviewed and changes to be made if required, and if it's good enough to be merged perhaps for Qt6 branch?

Thanks.

**Comment by sjemens** [comment]
Since the tests are passing it is probably alright, but I will give it a deeper look in the weekend.

**Comment by sjemens** [comment]
There is now a [Qt 6.0 branch](https://github.com/sjemens/qsqlcipher-qt5/tree/6.0)
